### ISSUE TITLE
Large amount of "New chapter" notifications

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#101]
Seems like an issue on backend. I keep getting new chapter notifications for manga that I've already caught up to. Issue seems common to bato.to titles. The URL between my most current read and the most recent release are also the same. 

Example: 
http://i.imgur.com/XFbmDPN.png

**Comment by DakuTree** [comment]
Whenever bato.to updates a chapter it's URL changes (`/reader#CHAPTERID` < This bit), and this is what we use to check for new chapters since we can't rely on chapter numbers here.  
Only thing you can do here is just manually mark them as read/ignored again.  

You got a bit unlucky with so many getting updated at once though. I'm following around 800~ series and only see this happening around once per week..
