### ISSUE TITLE
Add a manual update button

### ISSUE THREAD

**Issue by rjbs91** [DakuTree/manga-tracker#103]
Hi. Could it be possible to add a button to manually update the list? Or a setting to change the time between updates. Thanks in advance :)

**Comment by DakuTree** [comment]
We're not allowing manual updating as we want to limit the amount of requests we send to sites as much as possible.  
Mainly to avoid getting IP blocked, as well as avoiding the possibility of slowing the site down to a crawl due to mass updates (like what AMR does).

Updates are every 12-16 hours (or every hour for MangaFox/Batoto), so there isn't much need for a manual update anyway.
