### ISSUE TITLE
Auto-Tracking Batoto never initializes

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#123]
As far as I know, auto-tracking will not work with batoto due to how the userscript is currently setup. The autotracking function is currently inside the presetupviewer function, meaning that it is only called during this time period.

However, the current batoto site object overrides the presetupviewer function resulting in a loss of this function occurring. I couldn't decide whether to include a fix via changing specifically the batoto function, since it's the only one that overwrites the presetupviewer function, but I feel like it might appear in future site additions, so its best to address it earlier. 

See [auto-track](https://github.com/DakuTree/manga-tracker/blob/master/public/userscripts/manga-tracker.user.js#L655-L659) and [bato.to replacement](https://github.com/DakuTree/manga-tracker/blob/master/public/userscripts/manga-tracker.user.js#L1341-L1355)

**Comment by DakuTree** [comment]
The auto-tracking is actually called during the callback, so it's still called properly.  
The real problem seems to be with the `$(window).on('load')` not triggering because the event was already called before we could setup the auto-tracking.

bato.to should now call it without the window load event in postSetupViewer which fixes the problem.

**Comment by Vesnyx** [comment]
Yeah, you're totally right. My bad lol. I need to work on my code comprehension. Also, why not put config check on the postSetupViewer function? I realize its currently a stub, but wouldn't it help future-proof it rather than assigning it a variable as it is right now?
