### ISSUE TITLE
Sort latest release by date

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#134]
Currently sorting by latest release does so alphanumerically, meaning that the latest release is actually just the largest chapter. It could be changed to sort by date of last update.

**Comment by DakuTree** [comment]
Added as of dafd2ff08f28db40c64d36f8dbfe79ba6047991b & f0a23c0af30d943e3cb5075c877b933ba6a3b300.

The existing "Latest Release" sort method now sorts by datetime rather than alphanumerically.  
Also added a new "Unread (Latest Release)" sort which does the same as above, but stickies the unread series at the top.

**Comment by Vesnyx** [comment]
The sort method on the settings works fine. Tablesort doesn't seem to use the same rules.

**Comment by DakuTree** [comment]
Tablesort should work the same as of 7809c24df8451a06dbe9edc22ac373561d52b61d.
