### ISSUE TITLE
MangaFox / Mangahere switched to https

### ISSUE THREAD

**Issue by groundhogxp** [DakuTree/manga-tracker#213]
I don't know what new changes Mangahere recently went through, but it seems to have stopped working with this specific website.

**Comment by DakuTree** [comment]
Both MangaHere & MangaFox appear to have switched to using https. Should be working now.

Might still be some issues with image loading as it seems they are no longer using http://l.mfcdn.net as the image domain, and are instead using https://lmfcdn.secure.footprint.net which appears to be flagged by uMatrix.
Appears to be due to caused by the [hpHosts](https://hosts-file.net/?s=secure.footprint.net) list.

**Comment by DakuTree** [comment]
Few other issues I've spotted which I'll try and get fixed ASAP:
- [ ] MangaFox is no longer using the mobile viewer to load images faster.
- [ ] MangaHere isn't loading the first image. This appears to be caused by the /1.html url redirecting to the non-page url which is also https.
