### ISSUE TITLE
Greasemonkey Update

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#222]
Saw this on another userscript, and since we tend to use some of the methods, I thought I'd add it here:

> Because Greasemonkey are updating to be compatible with the new Browser Extension API, they have made a backwards incompatible change.
> 
> URL's to there blog:
> http://www.greasespot.net/2017/09/greasemonkey-4-announcement.html
> http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
> 
> TL;DR:
> 
> The new greasemonkey is going to use GM. variable instead of the old GM_ (both in grand and code)
> GM. returns a promise instead of a value.
> Version 4 is still in alpha and not finalized yet, but i thought a heads up would be in place here

Alpha is here: 
https://github.com/greasemonkey/greasemonkey/releases

**Comment by DakuTree** [comment]
Interesting.

Curious to see if the other userscript extensions will follow with this as well, since most of them try to support the GM_ functions for compatability reasons.  
TamperMonkey appears to have [experimental support on FF](https://tampermonkey.net/changelog.php?ext=dhdg&show=fire#v4.5.5570), but not on other browsers yet.

> As of today, there is no support for: GM_log (use console.log), GM_addStyle, GM_registerMenuCommand, nor GM_getResourceText.

Hopefully this will get sorted since we use addStyle/getResourceText quite a bit.

**Comment by DakuTree** [comment]
Just noticed that the userscript is completely broken under GreaseMonkey now. Had been testing it in FF on TamperMonkey by mistake (which I didn't realize I had installed...). Whoops.  

The issue I listed above is still an issue as well, which makes supporting GreaseMonkey is a bit of an issue.  
We need getResourceText to allow us to use font awesome properly over a CDN, as well as situational loading of the userscript css.  
addStyle could easily be replaced with a polyfill or something.

**Comment by DakuTree** [comment]
Have made considerable progress on this today, at least to the point where the script actually loads.
Problem with trying to do development for GM is it's an absolute nightmare trying to figure out what exactly went wrong. This is mainly due to the console (both of them) not actually returning any useful data about what went wrong, or why.

Still have a few issues need to work on, but will try and get them done tomorrow:
* GM_addValueChangeListener doesn't exist in GM, seems to be TM specific. Not a big issue since we can just do a check for it, it just means no auto-updating the dashboard if it's open in another tab.
* As far as I can tell, GM.xmlHttpRequest doesn't pass along your browser cookies, which means we currently can't get an API key, but we could probably just move the API generation completely to the site side of things which should fix that.
* And for site support (topbar/viewer), no idea yet. Shouldn't be too much issue, but we'll see I guess...

**Comment by DakuTree** [comment]
Implemented as of 305d32eff2dd90906e7ffd9509ab1a554200f927.

Everything seems to work as far as I can tell, par the issue I mentioned with GM_addValueChangeListener.  
TamperMonkey also seems to work with polyfill which is good.

Will keep this open for the time being incase in bugs pop up.
