### ISSUE TITLE
MangaZuki Site Update

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#229]
Seems like the site changed its whole reader and a bunch of manga are now missing. Don't know if they'll add them back. Either way, the reader looks similar to the Fallen Angels one.

**Comment by DakuTree** [comment]
Looks like it's using some kind of WordPress plugin/theme. Not having much luck finding what one though.

**Comment by DakuTree** [comment]
Mangazuki should work again as per the above commit. Also fixed Fallen Angels Scans since that was broken too.

I've also went and disabled all series not on the new reader, and tweaked the only 2 that are so they should just work automatically. Anything else will have to be re-added manually sadly.
