### ISSUE TITLE
MAL syncing not working

### ISSUE THREAD

**Issue by doutatsu** [DakuTree/manga-tracker#238]
Most of the manga I have MAL ID added doesn't sync. When I mark a chapter complete, it just says "MAL ID is not set" which is not the case...

**Comment by Vesnyx** [comment]
So, I've looked into it a bit and I've found some other information.

When it tries to pull the server mal_id parameter, it seems to fail on its call and returns a null value. Maybe its because it tries to pull the user information for the ID instead. If I manually set the ID, then it seems to work fine and pulls the data successfully. 

At the moment, it seems like the issue is primarily related to the server set MAL IDs. @doutatsu do any of the series that you manually set work?

**Comment by doutatsu** [comment]
Yup, can confirm that its only those with already known MAL IDs that are not working. If I manually set an ID for them, it syncs

**Comment by DakuTree** [comment]
Fixed as per f2d2ea786b4bc323eae5bb1732c4318fddef3650.
