### ISSUE TITLE
"Something went wrong" during "Update" (book icon)

### ISSUE THREAD

**Issue by mikken** [DakuTree/manga-tracker#241]
Hello, updating manga stopped working for me on every manga website.
It pops up this message: "Something went wrong".
I have tried re-logging in trackr.moe, updating API key, reloading webpage with the chapter, nothing helped.

I use:
Firefox 57.0.1
Tampermonkey v4.5.5660
Manga Tracker 1.8.11

**Comment by DakuTree** [comment]
Not too sure what is causing this. Tried to reproduce with no luck.

If you could send the console log next time this happens and also links of the sites this is occurring, both  would help a lot
To open console: Menu > Web Developer > Web Console or CTRL+SHIFT+K

**Comment by mikken** [comment]
Page address: `https://readms.net/r/one_piece/888/4758/1`
After the book button is pressed, nothing else is printed on console.

I tried debug mode on userscript.js and it fails after I step over line 373 (it is an empty line inside a statement).
After that it jumps to line 408 and outputs the error message.

**Comment by mikken** [comment]
This is where it fails:
```
$.post(main_site + '/ajax/userscript/update', params, function (json) {
/** @param {{mal_sync:string, mal_id:int, chapter:string}} json **/
GM_setValue('lastUpdatedSeries', JSON.stringify(Object.assign(params, json, {url: location.href, chapterNumber: (_this.chapterNumber !== '' ? _this.chapterNumber : _this.chapter)})));
```

**Comment by Vesnyx** [comment]
Don't know if it's the same error, but it might be caused by trying to load the next chapter before the previous one has loaded completely. I can reproduce this on any supported site that loads the viewer. It looks like the request to trackr's update gets canceled as the new page loads, resulting in this error message. 

However, @mikken 's issue might be completely different. Do you have any other extensions installed (uBlock, AdBlock, uMatrix, Disconnect, etc.)? They might be interfering with the request, but to my knowledge, none of them have caused these types of issues.

**Comment by mikken** [comment]
I have uBlock Origin and Privacy Badger.
That's right, Privacy Badger's heuristics identified trackr.moe as a tracker, I allowed this domain back and updating is back to normal.
