### ISSUE TITLE
Ability to manually update the list, or more frequent updates

### ISSUE THREAD

**Issue by honephiim** [DakuTree/manga-tracker#298]
## Feature/Site Request

**What is the feature?**

I know that we have an explanation on why the list isn't updated that frequently, but even so, I was wondering if it was possible to give us the ability to update the list at a time of our choosing in combination with the regular updates. I think that would be really helpful. Maybe limiting us to a number of times that we could do that a day wouldn't make it as problematic? 
Or, if this isn't possible, could we get at least more frequent updates?

**Other relevant information:**

The reason that I'm asking this, is because since I started using the website, in many instances, when I read everything that was marked with having a new chapter, later the day I usually find out that there is more chapters to read, but since the update hadn't come out yet, I was unaware of them. Sometimes even, I only find out the day after the chapter is released. Which is quite frustrating. 

I started using an extension called "Feedbro", which tells me right away when a new chapter comes out. Plus, the option to update all manually. Therefore here I am asking if it's possible to do the same here.

**Comment by DakuTree** [comment]
Manually updating the list is not going to happen. People would just end of forcing updates for the sake of it, even if there isn't any updates, and it kinda goes against the whole premise of why I set up trackr.moe to begin with.

As for updating more frequently, that can problem be done.  
At the moment our update speed depends on if the site is using a custom updater or not (every hr, compared to every 14~). 41 of 57 sites currently do which is great, but the remaining 16 are some of the bigger ones (MangaHere, MangaStream, Webtoons, MangaDex etc.) which is probably why you're seeing the slower updates.  
Shall have a look at getting some of these added today which should hopefully help things.

**Comment by honephiim** [comment]
Like I mentioned, isn't it possible to limit the number of times that we would do that? For example, only 3 times in a space of 24 hours. 

> and it kinda goes against the whole premise of why I set up trackr.moe to begin with.

How so?

So, there isn't much that you can do when it comes to those websites?

> Shall have a look at getting some of these added today which should hopefully help things.

I think that my English is getting in the way... what do you mean by that?

**Comment by Vesnyx** [comment]
> Like I mentioned, isn't it possible to limit the number of times that we would do that? For example, only 3 times in a space of 24 hours.

Here's a thought. If we have 500 users on at one time, and they all have the same manga on their lists, there will be 500 queries for that 1 manga. Now if that amount is scaled up for having greater than 1 manga, there'll be numerous requests. This of course assumes that people are using the manual update at the same time. We don't want to spam requests like that.

I can't speak for the site's premise, but what I thought of the site was a simple way to keep track of manga from multiple sites. 

> what do you mean by that?

Addressing your last question, @DakuTree will be implementing custom updater's (I believe) for the sites that don't already have it, allowing for hourly updates, which should mitigate the need for a manual update.

**Comment by honephiim** [comment]
Thank you for the explanation. I understand why it can't be done. 
I was just trying to suggest some stuff. Though, without the proper knowledge behind it, it is quite hard to do so. 

>I thought of the site was a simple way to keep track of manga from multiple sites.

Same here, but I don't think that what I said would go against it. 

>DakuTree will be implementing custom updater's (I believe) for the sites that don't already have it, allowing for hourly updates,

Oh, so that can be implemented on the sites? I was thinking that was how the site was structured and trackr.moe couldn't do anything about it. Again, not having any knowledge about stuff like this makes it quite hard to know what is going on...

>which should mitigate the need for a manual update.

Indeed. It definitely does.

**Comment by DakuTree** [comment]
> Like I mentioned, isn't it possible to limit the number of times that we would do that? For example, only 3 times in a space of 24 hours.

@Vesnyx really hit on nail on the head here.  
It's not a bad idea, it just wouldn't really work unless we put on some major limititions of how much would be updated. Even then, the custom updater removes the need for it.

> How so?  
> ...  
> I thought of the site was a simple way to keep track of manga from multiple sites.

That is what the site is, but the reason it was setup was more to replace [AllMangasReader](http://www.allmangasreader.com/) and other similar exts/apps which weren't that great for the sites actually being tracked, namely since having a ton of people requesting updates for multiple series every x minutes isn't really that efficient, nor is it good on the sites being tracked.  

> Oh, so that can be implemented on the sites? I was thinking that was how the site was structured and trackr.moe couldn't do anything about it.

The reason most of the remaining sites hadn't got custom updaters yet was because I was wanting to use the same method we use with MangaFox & Batoto, which is using the following page. Problem is that is a bit more tricky, and in some cases impossible to setup for some sites.  
This being said, had a bit of success with all the FoolSlide sites using the latest releases page for the custom updater, and that would probably work for the remaining ones. Just hadn't gotten around to implementing it yet.

**Comment by honephiim** [comment]
Then it's a friendly tracker? ...and what I said, despite making sense as a tracker, went against the friendly part? 

>Problem is that is a bit more tricky, and in some cases impossible to setup for some sites.

>This being said, had a bit of success with all the FoolSlide sites using the latest releases page for the custom updater, and that would probably work for the remaining ones.

Then it's just a matter of testing it out to find out?  
I will be hoping for the best!

I don't think that I mentioned yet,  but I'm a big fan of trackr.moe. I can't even begin to describe how helpful it is. Thank you for making and continuing to develop it.

**Comment by DakuTree** [comment]
> Then it's just a matter of testing it out to find out?

Actually done this since I last posed.  
All sites with the exception of LHTranslation & WebToons now use the custom updater. LHTranslation may get it at some point, however WebToons won't get it unless they add somewhere on their site to see latest releases (with chapter & date info).

> I don't think that I mentioned yet, but I'm a big fan of trackr.moe. I can't even begin to describe how helpful it is. Thank you for making and continuing to develop it.

Glad it helps!

Going to close this since the issue has been solved with the new custom updaters.
