### ISSUE TITLE
not changing pages on Fallen Angels Scans

### ISSUE THREAD

**Issue by honephiim** [DakuTree/manga-tracker#321]
## Bug report

**What is the bug?**

I can't switch pages on https://manga.fascans.com

**Please provide steps to reproduce:**

just open any chapter and try changing pages. 
This one for example: https://manga.fascans.com/manga/osananajimi-ni-najimitai/3/1

**Where did the bug happen? (If applicable)**

Any chapter of this website: https://manga.fascans.com/

**Comment by Vesnyx** [comment]
So this occurs because of how we currently call the functions. Fallen Angel Scans uses myMangaReaderCMS, in which we call a removal function after the topBar is generated. This removes the next page and chapter stuff. However, since the topBar is generated in all instances (multi-page or single-page), the default next page script is broken since we "accidentally" removed the values for it to redirect to. 

TBH, this could be fixed if we implement the postSetupViewer function to only remove elements if we have loaded the viewer. 

Also, this bug is common to all myMangaReaderCMS sites.

**Comment by Vesnyx** [comment]
Forgot to mention this, but postSetupViewer is still a stub in the userscript. 

```
	/**
	 * This is currently just a stub and isn't used yet!
	 *
	 * @function
	 * @todo Add definition for postSetupViewer
	 * @alias sites.*.postSetupViewer
	 * @name  base_site.postSetupViewer
	 *
	 * @param {jQuery=} topbar
	 */
	postSetupViewer : function(topbar) {}, // jshint ignore:line
```
This generates an error later on when this function is called.
