### ISSUE TITLE
Rate limit reached (Status: 429)

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#97]
I just added a ton of series to my list, many aren't getting tracked due to this rate limit. Had to check in console log to see what the issue was. Create a notification to tell user that there is a rate limit and when it will be over.

**Comment by Vesnyx** [comment]
Also, although the rate limit was reached, it seems like the favoriting mechanism follows a different limit. I could favorite the series that weren't tracked, and the history said they were added to my list, but did not actually show up. The favorite displays them, however.

**Comment by DakuTree** [comment]
> I just added a ton of series to my list, many aren't getting tracked due to this rate limit.

This should be fixed now. Somehow had the rate limit at 250 requests an hour by accident.  
As for the lack of notification, there _should_ be an alert popup when there is any kind of failure with requests, will have to check why that isn't showing.

> Also, although the rate limit was reached, it seems like the favoriting mechanism follows a different limit.  

Favouriting did have a separate limit but that has been removed.  

> I could favorite the series that weren't tracked, and the history said they were added to my list, but did not actually show up. The favorite displays them, however.

This is intentional.  
The favourite system requires the user to have the series followed in their list, but if they favourite a chapter from a series they aren't following we simply add the series as inactive (so it doesn't show). Any action done after that would mark that series as active which would make it show properly in the list.
